const relativeUrls = [
	"/autogenerated-1/en/",
	"/autogenerated-1/en/sub1",
	"/autogenerated-1/en/sub2",
	"/autogenerated-1/en/sub3",
	"/autogenerated-1/en/sub4",
	"/autogenerated-1/en/sub5",
	"/autogenerated-1/en/sub6",
	"/autogenerated-1/en/sub7",
	"/autogenerated-1/en/sub8",
	"/autogenerated-1/en/sub9",
	"/autogenerated-1/en/sub10",
	"/autogenerated-1/en/sub11",
	"/autogenerated-1/en/sub12"
];

module.exports = {
	relativeUrls,
};
