const urls = [
	"/autogenerated-1/en/",
	"/autogenerated-1/en/sub1",
	"/autogenerated-1/en/sub2",
	"/autogenerated-1/en/sub3",
	"/autogenerated-1/en/sub4",
	"/autogenerated-1/en/sub5",
	"/autogenerated-1/en/sub6",
	"/autogenerated-1/en/sub7",
	"/autogenerated-1/en/sub8",
	"/autogenerated-1/en/sub9",
	"/autogenerated-1/en/sub10",
	"/autogenerated-1/en/sub11",
	"/autogenerated-1/en/sub12"
];

module.exports = function(count, seed) {
	generator = SeedRandom(parseInt(seed));
	limit = urls.length - 1;

	var relativeUrls = [];
	var loops = 0;
	while (relativeUrls.length < count && loops < limit) {
		index = generator(limit);
		relativeUrl = urls[index];
		if (relativeUrl.indexOf('-1/') === -1) {
			relativeUrls.push(urls[index]);
		}
		loops++;
	}

	return {
		relativeUrls
	};
};


function SeedRandom(state1, state2) {
	var mod1 = 4294967087
	var mul1 = 65539
	var mod2 = 4294965887
	var mul2 = 65537
	if (typeof state1 != "number") {
		state1 = +new Date()
	}
	if (typeof state2 != "number") {
		state2 = state1
	}
	state1 = state1 % (mod1 - 1) + 1
	state2 = state2 % (mod2 - 1) + 1

	function random(limit) {
		state1 = (state1 * mul1) % mod1
		state2 = (state2 * mul2) % mod2
		if (state1 < limit && state2 < limit && state1 < mod1 % limit && state2 < mod2 % limit) {
			return random(limit)
		}
		return (state1 + state2) % limit
	}

	return random;
}
